version: "2"
run:
  tests: true
linters:
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gomoddirectives
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
  disable:
    - depguard
    - dupl
    - goconst
    - gocyclo
    - lll
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/utilitywarehouse/castle-go)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
